/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedAppsIndexRouteImport } from './routes/_authed/apps/index'
import { Route as AuthedAppsSlugRouteRouteImport } from './routes/_authed/apps/$slug/route'
import { Route as AuthedAppsSlugIndexRouteImport } from './routes/_authed/apps/$slug/index'
import { Route as AuthedAppsSlugApiKeysRouteImport } from './routes/_authed/apps/$slug/api-keys'
import { Route as AuthedAppsSlugMembersRouteImport } from './routes/_authed/apps/$slug/members'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAppsIndexRoute = AuthedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAppsSlugRouteRoute = AuthedAppsSlugRouteRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAppsSlugIndexRoute = AuthedAppsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppsSlugRouteRoute,
} as any)
const AuthedAppsSlugApiKeysRoute = AuthedAppsSlugApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedAppsSlugRouteRoute,
} as any)
const AuthedAppsSlugMembersRoute = AuthedAppsSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedAppsSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof AuthLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/users': typeof AuthedUsersRoute
  '/apps/$slug': typeof AuthedAppsSlugRouteRouteWithChildren
  '/apps/': typeof AuthedAppsIndexRoute
  '/apps/$slug/api-keys': typeof AuthedAppsSlugApiKeysRoute
  '/apps/$slug/members': typeof AuthedAppsSlugMembersRoute
  '/apps/$slug/': typeof AuthedAppsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof AuthLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/users': typeof AuthedUsersRoute
  '/apps': typeof AuthedAppsIndexRoute
  '/apps/$slug/api-keys': typeof AuthedAppsSlugApiKeysRoute
  '/apps/$slug/members': typeof AuthedAppsSlugMembersRoute
  '/apps/$slug': typeof AuthedAppsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/apps/$slug': typeof AuthedAppsSlugRouteRouteWithChildren
  '/_authed/apps/': typeof AuthedAppsIndexRoute
  '/_authed/apps/$slug/api-keys': typeof AuthedAppsSlugApiKeysRoute
  '/_authed/apps/$slug/members': typeof AuthedAppsSlugMembersRoute
  '/_authed/apps/$slug/': typeof AuthedAppsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/users'
    | '/apps/$slug'
    | '/apps/'
    | '/apps/$slug/api-keys'
    | '/apps/$slug/members'
    | '/apps/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/users'
    | '/apps'
    | '/apps/$slug/api-keys'
    | '/apps/$slug/members'
    | '/apps/$slug'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_auth/login'
    | '/_authed/profile'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/apps/$slug'
    | '/_authed/apps/'
    | '/_authed/apps/$slug/api-keys'
    | '/_authed/apps/$slug/members'
    | '/_authed/apps/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/apps/': {
      id: '/_authed/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthedAppsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/apps/$slug': {
      id: '/_authed/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AuthedAppsSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/apps/$slug/': {
      id: '/_authed/apps/$slug/'
      path: '/'
      fullPath: '/apps/$slug/'
      preLoaderRoute: typeof AuthedAppsSlugIndexRouteImport
      parentRoute: typeof AuthedAppsSlugRouteRoute
    }
    '/_authed/apps/$slug/api-keys': {
      id: '/_authed/apps/$slug/api-keys'
      path: '/api-keys'
      fullPath: '/apps/$slug/api-keys'
      preLoaderRoute: typeof AuthedAppsSlugApiKeysRouteImport
      parentRoute: typeof AuthedAppsSlugRouteRoute
    }
    '/_authed/apps/$slug/members': {
      id: '/_authed/apps/$slug/members'
      path: '/members'
      fullPath: '/apps/$slug/members'
      preLoaderRoute: typeof AuthedAppsSlugMembersRouteImport
      parentRoute: typeof AuthedAppsSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedAppsSlugRouteRouteChildren {
  AuthedAppsSlugApiKeysRoute: typeof AuthedAppsSlugApiKeysRoute
  AuthedAppsSlugMembersRoute: typeof AuthedAppsSlugMembersRoute
  AuthedAppsSlugIndexRoute: typeof AuthedAppsSlugIndexRoute
}

const AuthedAppsSlugRouteRouteChildren: AuthedAppsSlugRouteRouteChildren = {
  AuthedAppsSlugApiKeysRoute: AuthedAppsSlugApiKeysRoute,
  AuthedAppsSlugMembersRoute: AuthedAppsSlugMembersRoute,
  AuthedAppsSlugIndexRoute: AuthedAppsSlugIndexRoute,
}

const AuthedAppsSlugRouteRouteWithChildren =
  AuthedAppsSlugRouteRoute._addFileChildren(AuthedAppsSlugRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAppsSlugRouteRoute: typeof AuthedAppsSlugRouteRouteWithChildren
  AuthedAppsIndexRoute: typeof AuthedAppsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAppsSlugRouteRoute: AuthedAppsSlugRouteRouteWithChildren,
  AuthedAppsIndexRoute: AuthedAppsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
